---
#- name: "update apt packages"
#  become: true
#  become_method: sudo
#  apt:
#    update_cache: yes

#- name: "upgrade packages"
#  become: true
#  apt:
#    upgrade: "yes"

  
#- name: "Install Python"
#  become: true
#  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
# changed_when: false
#- name: Copy files from CircleCI to EC2 server
#  copy:
#    src: /root/project/backend
#    dest: /home/ubuntu

#- name: "Stop PM2"
#  ignore_errors: yes
# shell: |
#   cd /home/ubuntu/backend
#  pm2 stop backend
#    pm2 delete backend
- name: Install node dependencies
  shell: |
    cd /home/ubuntu/backend    
    npm install 
    npm run build
    
- name: "Run node migrations and save to https://memstash.io/"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt
    export CIRCLE_WORKFLOW_ID="{{ CIRCLE_WORKFLOW_ID }}"
    echo CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}
    curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" --request PUT --data $( grep -c "No migrations are pending" migrations.txt ) https://api.memstash.io/values/dbmigration_status
  register: migration_output
  
  - debug:
    msg: "{{ migration_output.stdout_lines }}"

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --run "start:dev"
