---

- name: "Copy backend files to remote server"
  copy:
    dest: /home/ubuntu/
    src: /root/project/backend.tar.gz

- name: "Unzip backend files"
  shell: |
    cd /home/ubuntu
    mkdir backend
    tar -xzvf backend.tar.gz -C .
    
- name: "Build npm packages"
  shell: |
    cd /home/ubuntu/backend
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable
    PATH="$PATH"
    npm i
    npm run build
    
- name: "run migrations and save status to memstash.io"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt
    export CIRCLE_WORKFLOW_ID="{{ CIRCLE_WORKFLOW_ID }}"
    echo CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}
    curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" --request PUT --data $( grep -c "No migrations are pending" migrations.txt ) https://api.memstash.io/values/migration_status
  register: migration_output
 
  shell: |
    cd /home/ubuntu/backend
    ls
    pm2 start -x -i 4 --name "app" ./dist/main.js
 #   pm2 start npm -- run "start:dev"

