---

- name: Copy files from circleci to backend server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/

- name: Build node service
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
  
- name: Start pm2 service
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start

