---
- name: "Upgrade packages"
  become: true
  apt:
    upgrade: "yes"

- name: Executing node
  become: true
  shell: |
 #   pm2 start npm -- run "start:dev"
    pm2 start -x --name "app" ./dist/main.js

