---

- name: Copy files from circleci to backend server
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Unzip backend files
  shell: |
    cd /home/ubuntu
    mkdir backend
    tar -xzvf backend.tar.gz -C .
    
- name: Build node service
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
    
- name: "Start pm2 service"
  shell: |
    cd /home/ubuntu/backend
    ls
    pm2 start npm -- run "start:prod"

