version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:
  hello-world: # Delete this job when you get started
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  analyze-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Analyze frontend
          command: |
            cd frontend
            npm i
            npm audit fix --audit-level=critical --force
        
  analyze-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Analyze backend
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical --force
            
  build-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
            
  build-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
  test-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm i
            npm audit fix --audit-level=critical --force
            npm run test
  test-backend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Test backend
          command: |
            cd backend
            npm i
            npm run test
  
  deploy-frontend-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy frontend infrastructure
          command: |
            aws cloudformation create-stack \
              --stack-name autofrontenduda \
              --template-body file://./.circleci/files/frontend.yml \
              --region us-east-1 
           
  deploy-backend-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy backend infrastructure
          command: |
            aws cloudformation create-stack \
              --stack-name autobackenduda \
              --template-body file://./.circleci/files/backend.yml \
              --region us-east-1 
              
  config-infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0a:ab:9c:78:ab:04:4e:29:a7:dc:63:62:36:ad:c8:c4"]
      - run:
          name: "Install dependencies"
          command: |
            apk add --update ansible
      - run:
          name: "Save IP address of EC2 instance to inventory file"
          command: |
            cd .circleci/ansible
            echo "[all]" > inventory.txt
            $(aws ec2 --region us-east-1 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text) >> inventory.txt
            pwd
            cat inventory.txt      
      - run:
          name: "Configure ubuntu server"
          command: |
            cd .circleci/ansible \
            ansible-playbook -i inventory.txt main.yml			

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - hello-world
      
  frontend:
    jobs:
      - analyze-frontend
      - build-frontend:
          requires:
            - analyze-frontend   
      - test-frontend:
          requires:
            - build-frontend
      - deploy-frontend-infra:
          requires:
            - test-frontend
            
  backend:
    jobs:
      - analyze-backend
      - build-backend: 
          requires:
            - analyze-backend
      - test-backend:
          requires:
            - build-backend
      - deploy-backend-infra:
          requires:
            - test-backend
      - config-infra:
          requires:
            - deploy-backend-infra

  			
