version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

commands:
  destroy-environment:
    description: Destroy all cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Delete all files in the current S3 bucket
          command: |
            if aws s3api head-bucket --bucket udapeople-frontend-${CIRCLE_WORKFLOW_ID}
            then
              aws s3 rm s3://udapeople-frontend-${CIRCLE_WORKFLOW_ID}/ --recursive
            fi
          when: on_fail
      - run:
          name: Delete the current AWS CloudFormation stacks
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID}
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID}
          when: on_fail

  revert-migration:
    description: Revert the last migration
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical --force
            npm run migrations:revert

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Frontend Code
          command: |
            cd frontend
            npm i
            npm run build
            
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Backend Code
          command: |
            cd backend
            npm i
            npm run build
            
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm i
            npm audit fix --audit-level=critical --force
            npm run test
            
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test Backend Code
          command: |
            cd backend
            npm i
            npm run test
            
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Analyze and resolve frontend dependencies
          command: |
            cd frontend
            npm i
            npm audit fix --audit-level=critical
            
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Analyze and resolve backend dependencies
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical
            
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install tar gzip
      - run:
          name: backend infra
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
              --parameter-override ID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udaPeople
      - run:
          name: Save the URL of EC2 instance to https://memstash.io/
          command: |
            HOST_NAME=$(aws ec2 describe-instances --region us-east-1 --query "Reservations[*].Instances[0].PublicDnsName" --output text)
            echo ${HOST_NAME}
            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" --request PUT --data ${HOST_NAME}  https://api.memstash.io/values/host_name 
            
      - run:
          name: frontend infra
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udaPeople
              #ARN=$(aws s3 ls | grep udapeople)
              #echo "ARN=$ARN"
              #curl -H "Content-Type: text/plain" \
              #     -H "token: 97jm1945-45k1-4b71-896f-c1i276462430" \
              #     --request PUT --data 
              #     "https://api.memstash.io/values/arn_${CIRCLE_WORKFLOW_ID}"
      - destroy-environment

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            apk add --no-cache openssh-client
            apk add --no-cache --upgrade bash
            pip install awscli
      - add_ssh_keys:
          fingerprints: ["0a:ab:9c:78:ab:04:4e:29:a7:dc:63:62:36:ad:c8:c4"]
      - run:
          name: Set up inventory file
          command: |
            cd .circleci/ansible
            echo "[all]" > ./inventory
            export HOST_NAME=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/host_name) 
            echo ${HOST_NAME} >> ./inventory
            echo "Inventory contents:"
            cat ./inventory
      - run:
          name: Configure server with ansible
          command: |
            cd .circleci/ansible
            ansible-playbook -i ./inventory main.yml
      - destroy-environment

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            cd backend
            npm install
            MIGRATED=$(npm run migrations)
      - run:
          name: Send migration result to memstash
          command: |
            if grep -q "success!" "$MIGRATED"
            then
              curl --request GET https://api.memstash.io/values/migration
            fi
      - destroy-environment

  deploy-frontend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache tar
            apk add --no-cache gzip
            apk add --no-cache ansible
            apk add --no-cache nodejs
            apk add --no-cache npm
            pip install awscli
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL=$API_URL" >> frontend/.env
            echo "${API_URL}"
            echo "AWS_DEFAULT_REGION=us-east-1" >> frontend/.env
            echo "AWS_ACCESS_KEY_ID=AKIARYWOGL52YX34PL2U" >> frontend/.env
            echo "AWS_SECRET_ACCESS_KEY=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" >> frontend/.env
            echo "TYPEORM_CONNECTION=postgres" >> frontend/.env
            echo "TYPEORM_DATABASE=postgres" >> frontend/.env
            echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> frontend/.env
            echo "TYPEORM_HOST=postgres.cetcozppgsui.us-east-1.rds.amazonaws.com" >> frontend/.env
            echo "TYPEORM_MIGRATIONS=./src/migrations/*.ts" >> frontend/.env
            echo "TYPEORM_MIGRATIONS_DIR=./src/migrations" >> frontend/.env
            echo "TYPEORM_PORT=5432" >> frontend/.env
            echo "TYPEORM_USERNAME=postgres" >> frontend/.env
            echo "TYPEORM_PASSWORD=udapost123" >> frontend/.env
            echo "Frontend env contents:"
            cat frontend/.env
      - run:
          name: "Baking backend API_URL into the front-end"
          command: |
            npm install webpack-dev-server -g
            cd frontend
            npm i
            npm run build      
 #     - run:
 #         name: Deploy frontend 
 #         command: |
 #           cd frontend
 #           npm install
 #           npm run build
      - run: 
          name: Copy built frontend files to the S3 bucket
          command: |
            aws s3 cp ./frontend/dist s3://udapeople-frontend-"${CIRCLE_WORKFLOW_ID}" --recursive  
      - destroy-environment
      - revert-migration

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0a:ab:9c:78:ab:04:4e:29:a7:dc:63:62:36:ad:c8:c4"]
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            pip install awscli
      - run:
          name: Set up inventory file
          command: |
            cd .circleci/ansible
            echo [all] >> ./inventory
            export HOST_NAME=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/host_name)
            echo ${HOST_NAME} >> ./inventory
            echo "Inventory contents"
            cat ./inventory    
      - run:
          name: Build and deploy backend
          command: |
            printenv >> ./backend/.env
            cd backend
            npm i
            npm run build            
   #   - run:
   #       name: Run Ansible playbook
   #       command: |
   #         cd .circleci/ansible
   #         ansible-playbook -i ./inventory main.yml
   #         no_output_timeout: 30m
      - destroy-environment
      - revert-migration 

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            pip install awscli
      - run:
          name: Smoke test backend
          command: |
            export BACKEND_IP=$(aws ec2 --region us-east-1 describe-instances \
                  --filters Name=instance-state-name,Values=running \
                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
                  --output text)
            echo "${BACKEND_IP}"
            echo ${BACKEND_IP}
            APP_URL="http://${BACKEND_IP}:3030/api/status"
            echo ${APP_URL}
            curl ${APP_URL}
            if curl -s ${APP_URL} | grep "Ok"
            then
              return 1
            else
              return 0
            fi
      - run:
          name: Smoke test frontend
          command: |
            URL="http://udapeople-frontend-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com/#/employee
   
            if curl -s ${URL} | grep "Welcome"
            then
              return 0
            else
              return 1
            fi
      - destroy-environment
      - revert-migration

  cloudfront-update:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0a:ab:9c:78:ab:04:4e:29:a7:dc:63:62:36:ad:c8:c4"]
      - run:
          name: Install dependencies
          command: |
            apk add --update nodejs npm curl
            pip install awscli
      - run:
          name: Update cloudfront distribution
          command: |
            export OldWorkflowID=$(aws cloudformation \
              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
              --no-paginate --output text)
            export STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
              --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
            echo Old Workflow Id: "$OldWorkflowID"
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name udapeople-cloudfront \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udapeople &
            if [[ "$STACKS[@]" =~ "$OldWorkflowID" ]]
            then
              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
            fi
      - destroy-environment
      - revert-migration

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only:
                - master
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
   #  - cloudfront-update:
   #       requires: [smoke-test]
